# Generated by Django 4.2.3 on 2023-07-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
